services:
  cityflow:
    build: .
    runtime: nvidia
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility
    volumes:
      - ./code:/workspace/code
    working_dir: /workspace/code
    stdin_open: true
    tty: true
    command: /bin/bash
